# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
    - sequencing
pool:
  vmImage: ubuntu-latest

variables:
  AZURE_TEST: test

parameters:
  tables:
    - "table1"
    - "table2"

jobs:
- ${{ each job in parameters.tables }}:
  steps:
    - script: |
        echo ${{ job }}


# steps:
# # - ${{ each var in variables.secrets }}:
# #   - bash: |
# #       echo "##vso[task.setvariable variable=${{ var.key }}${{ var.value }}"

# - script: |
#     env 
#     packer build -force sequencing/sequencing.json
#   displayName: 'Execute Packer script for sequencing'
#   env:
#     AZURE_CLOUD: $(AZURE_CLOUD)
#     AZURE_SECRET: $(AZURE_SECRET)
#     AZURE_CLIENTID: $(AZURE_CLIENTID)
#     AZURE_SUBSCRIPTIONID: $(AZURE_SUBSCRIPTIONID)
#     AZURE_TENANTID: $(AZURE_TENANTID)
#     AZURE_LOCATION: $(AZURE_LOCATION)
