# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
    - 'sequencing/*'

pool:
  vmImage: ubuntu-latest

steps:
# - ${{ each var in variables.secrets }}:
#   - bash: |
#       echo "##vso[task.setvariable variable=${{ var.key }}${{ var.value }}"

- script: |
    env 
    pwd
    ls -la
    packer build -force sequencing/sequencing.json
  displayName: 'Execute Packer script for sequencing'
  env:
    AZURE_CLOUD: $(AZURE_CLOUD)
    AZURE_SECRET: $(AZURE_SECRET)
    AZURE_CLIENTID: $(AZURE_CLIENTID)
    AZURE_SUBSCRIPTIONID: $(AZURE_SUBSCRIPTIONID)
    AZURE_TENANTID: $(AZURE_TENANTID)
    AZURE_LOCATION: $(AZURE_LOCATION)
